### ISSUE TITLE
Raspberry Pico I2C Pinout Diagram Wrong

### ISSUE THREAD

**Issue by bjs2864** [raspberrypi/pico-feedback#197]
The pinout diagram for the Raspberry Pi Pico is incorrect. In the example code provided with the SDK, Pin 4 is identified as I2C Port 0 SDA and Pin 5 as I2C Port 0 SCL. From my testing, this seems correct. However, the pinout diagram identifies Pin 4 as I2C Port 1 SDA and Pin 5 as the I2C Port 1 SCL. The pinout diagram needs to be updated such that the labels on Pin 4 and Pin 6 are switched and the same with Pin 5 and Pin 7. This is incorrect here: https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html.  However, the datasheet for the RP2040 is correct, found here: https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html. I would highly recommend that someone double-checks the pinout diagram and make sure that it is correct. This diagram is found widely around the web and the inaccuracy is replicated all over.

**Comment by aallan** [comment]
> The pinout diagram for the Raspberry Pi Pico is incorrect. In the example code provided with the SDK, Pin 4 is identified as I2C Port 0 SDA and Pin 5 as I2C Port 0 SCL.

Yes, GP pin 4 and GP pin 5 are I2C0 SDA and I2C0 SCL.

> However, the pinout diagram identifies Pin 4 as I2C Port 1 SDA and Pin 5 as the I2C Port 1 SCL. 

You're mixing up Pico physical pin numbers (shown in grey) with GPIO pin numbers (shown in green). 

You're looking at pins GP2 and GP3 there, which are correctly labelled in the pinout diagram as I2C1 SDA and I2C1 SCL.

> The pinout diagram needs to be updated such that the labels on Pin 4 and Pin 6 are switched and the same with Pin 5 and Pin 7. However, the datasheet for the RP2040 is correct

The RP2040 datasheet doesn't discuss Pico physical pin numbers, only GPIO numbers. Since the SDK defaults are RP2040 defaults, not Pico defaults, pin numbering is based on GPIO (green) not physical pin (grey) pin numbers.

In hindsight I sort of regret adding the grey physical pins onto the pin out diagram at all, they're not amazingly useful and do cause some confusion, but there are physical pin numbers on the silkscreen so at the time I thought it was a good idea. 

You're not the first to get confused by this, however the pin out diagram is correct.
