### ISSUE TITLE
UART Character Frame Figure 61 wrong diagram.

### ISSUE THREAD

**Issue by envirocoder** [raspberrypi/pico-feedback#285]
Figure 61. claiming to be a UART character frame, isn't -- it's a IRDA transaction I think. Anyway, minor issue, but easily fixed with a copy and paste of the correct drawing.

I don't think I can fix the RP2040 datasheet myself, so didn't submit a pull request -- correct me if the source is somewhere and I'll fix it with a PR. And please don't take this as a criticism or nitpick, absolutely love the documentation.

**Comment by lurch** [comment]
Ah, cross-checking with https://documentation-service.arm.com/static/5e8e36c2fd977155116a90b5?token= it looks like a couple of our source-images were accidentally misnamed.
Thanks, will be fixed in the next release of the PDFs! (and you're correct in that the source for these isn't publicly available)
