### ISSUE TITLE
Max number of concurrent BLE connections

### ISSUE THREAD

**Issue by dakhnod** [raspberrypi/pico-feedback#313]
How many BLE connections to peripherals (in the center role) can the Pico W have at the same time?
In other works: to how many sensors (peripherals) can the Pico be connected at the same time?

What is the limitation of the BT hardware?
What is the limitation of the SDK?

**Comment by lurch** [comment]
ping @peterharperuk

**Comment by aallan** [comment]
I think the best answer we can give is that the limits for BTstack and the hardware — the CYW43439 chip itself — are separate. It’ll be whatever the smaller of the two turns out to be.

For BTstack, it’s limited by `min(MAX_NR_HCI_CONNECTIONS, MAX_NR_GATT_CLIENTS)` in code, and you should be able to increase those limit in your own code.

For the chip there’s a physical scheduling limit that results from the set of current connection parameters and a hard limit in the controller (due to memory limitations). I cannot find any hard numbers in the CYW4343 datasheet for the limits on the chip itself. At this point our guess is that this number will be higher than the number of connections you’re going to get in practice.

My recollection is the BLE specification has a maximum limit of 7 (or 8) depending on how you interpret the standard. But it’s been a while since I waded through it.

In any case, it should not be much worse than other current Bluetooth controllers. The TL;DR is “some.”
