### ISSUE TITLE
Read-only bootloader on Ventura 13.2.1

### ISSUE THREAD

**Issue by wxwot** [raspberrypi/pico-feedback#314]
I am mounting a Sparkfun Pro 2040 and putting it in bootloader mode to my laptop running Ventura 13.2.1 (updated today). I can see it mounted in Finder but when I try to copy a UF2 firmware file using drag and drop it does not work, and running `cp -X` or `rsync` from the terminal returns a message saying the Volume is a "Read-only file system". This was working OK before upgrading from MacOS 12.x.

**Comment by aallan** [comment]
I'm running 13.2 on my laptop, and have no issues with drag-and-drop of UF2 files, the issue was [fixed as of 13.1](https://github.com/raspberrypi/pico-sdk/issues/1081#issuecomment-1352096325). It's unlikely to have turned up again between 13.2 and 13.2.1, but I'll upgrade my laptop tomorrow and check.

**Comment by kilograham** [comment]
Works fine for me on 13.2.1 on Apple Silicon with a Pico
