### ISSUE TITLE
RP2040 datasheet: GPIO INVERT doesn't work. 

### ISSUE THREAD

**Issue by rewolff** [raspberrypi/pico-feedback#332]
For each GPIO pin you can set the output override to normal/invert/always high/always low. 

The OUTOVER "invert" is documented as "drive output from inverse of peripheral signal
selected by funcsel"

I tried this for PWM and it didn't work.

Now for PWM that isn't that bad, as I can invert it in the module, but this is not how it is written in the datasheet. 

(I initially wanted to invert it in the GPIO pin as that's a generic optiion I'm aware of, as opposed to the specific option that the PWM module happens to provide (and e.g. the UART doesn't!) )

**Comment by liamfraser** [comment]
Hi, can you provide your test case for this? We have a test case for this feature and I have just double checked it is working. How are you checking the output? If you are using the IO_BANK0_GPIO0_STATUS_OUTTOPAD_BITS field then you have to wait 2 clock cycles for the output to make it into the register. This is because there is a synchronizer to clk_sys. But the output to the actual pin should be inverted immediately. Perhaps try just by using the PROC gpio output. For example:

```
gpio_init(i);
gpio_put(i, 0);
gpio_outover(i, IO_BANK0_GPIO0_CTRL_OUTOVER_VALUE_INVERT);
// and then check the output value is a 1
```

**Comment by rewolff** [comment]
Here is my test code. Conclusion: It works as advertised. In my much bigger project it didn't seem to work. Excuse the noise. 


```
#include <stdio.h>
#include "pico/stdlib.h"
#include "hardware/pwm.h"


#define SWPWM 2
#define HW0 0
#define HW1 1

int main()
{
    int slice;
    stdio_init_all();
    puts("Hello, world!");

    gpio_init (SWPWM);
    gpio_set_dir (SWPWM, 1);
    gpio_set_outover (SWPWM, GPIO_OVERRIDE_NORMAL);

    gpio_set_function(HW0, GPIO_FUNC_PWM);
    gpio_set_function(HW1, GPIO_FUNC_PWM);
    gpio_set_outover (HW1, GPIO_OVERRIDE_INVERT);

    slice = pwm_gpio_to_slice_num(HW0);
    pwm_set_wrap(slice, 499);
    pwm_set_chan_level(slice, PWM_CHAN_A, 165);
    pwm_set_chan_level(slice, PWM_CHAN_B, 165);

    pwm_set_clkdiv_int_frac (slice, 250, 0);
    pwm_set_enabled(slice, true);

    while (1) {
       gpio_put (SWPWM, 1);
       sleep_us (333);
       gpio_put (SWPWM, 0);
       sleep_us (666);
    }
    return 0;
}
```
