### ISSUE TITLE
Incomplete and mis-formatted OpenOCD compilation documentation leads to broken build

### ISSUE THREAD

**Issue by Swiftloke** [raspberrypi/pico-feedback#376]
All of this was attempted on Ubuntu 22.04.

In the Pi Pico Getting Started guide, it's advised to use a downstream fork of OpenOCD to enable support for using the Pi Pico as a CMSIS-DAP compatible SWD adapter. Unfortunately, the documentation to do this has two problems, both of which lead to an inscrutable error when the compiled OpenOCD is actually used.

### Problem 1

First, OpenOCD cannot compile if the directions are followed by copy-pasting. Let's see why by checking the logs from compilation:

```
Enabled transports:
- USB ............................ no (missing: libusb-1.0)
- TCP ............................ yes

OpenOCD configuration summary
--------------------------------------------------
...

$ make
...
src/jtag/drivers/libusb_helper.h:12:10: fatal error: libusb.h: No such file or directory
   12 | #include <libusb.h>
      |          ^~~~~~~~~
```
Hold on. Wasn't libusb an explicit requirement? I swear I installed that. 

Well, it turns out the documentation has a formatting error. You see, the docs show the following:

```
 sudo apt install automake autoconf build-essential texinfo libtool libftdi-dev libusb-1.0-0-
dev
```
The problem is that **there is a line break in the libusb package name**, which means that when this is copy-pasted into a terminal, the ``dev`` part is left out, and therefore ``apt`` attempts to install ``libusb-1.0.0-`` which does not exist. It then ignores that package and proceeds to install the rest.

### Problem 2

Now with that fixed, the following error message is produced after "successfully" compiling OpenOCD and attempting to, say, program the "blink" example:

```
$ src/openocd -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 5000" -c "program blink/blink.elf verify reset exit"

Open On-Chip Debugger 0.12.0-g4d87f6d (2024-02-15-14:43)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html

embedded:startup.tcl:28: Error: Can't find interface/cmsis-dap.cfg
in procedure 'script'
at file "embedded:startup.tcl", line 28
```

Now why is this? There's a hint from back when we attempted to configure it...

```
OpenOCD configuration summary
...
CMSIS-DAP Compliant Debugger     no
```
Why is this important feature being disabled? Let's take a closer look with ``./configure --enable-cmsis-dap``...
```
configure: error: hidapi is required for the CMSIS-DAP Compliant Debugger
```
Oh. So ``hidapi`` is a requirement that's not listed in the documentation.

### Suggestions
Someone stumbled upon the libusb formatting issue [before me](https://github.com/raspberrypi/openocd/issues/75). Notably, the first bug with libusb actually manifested in the way the second bug did for me at first (compilation succeeds but built program is broken); only after trying to reproduce it a second time did I get an outright compile error. That seems to be the failure mode they encountered.

Someone also seems to have stumbled upon the hidapi issue [before me](https://forums.raspberrypi.com/viewtopic.php?p=2079148#p2079148). This was much harder to dig up as it required digging very deep into this random document on a forum.

I suspect that many others have encountered these issues and left them unreported. Here are my suggestions to prevent other people running into these in the future:

- Add ``libhidapi-dev`` to the list of dependencies to install the program.
- Remove the line break in the list of dependencies to install, making it one contiguous line. Alternatively, split the install commands into two llines.

**Comment by nathan-contino** [comment]
👏 Thanks so much for investigating and reporting this issue! I can't imagine how much time you wasted and how frustrated this must have made you, so allow me to apologize on behalf of our docs here. This is not the user experience we like to see.

It _does_ hearten me that you were still willing to report the issue after all of that frustration. Thank you for contributing back to the community. We docs folk are not omnipotent and can't possibly test everything. This is _exactly_ the kind of thing that we can easily miss, since we spend most of our time writing docs-as-code and not copy/pasting text out of the produced PDFs. 😓  

I've just fixed this issue in the source code by breaking up the installation command across two separate lines -- the newline in question was imposed by our PDF production pipeline, so there's no way to (easily, without getting into the plumbing) just make the line longer. Especially with `libhidapi-dev` added!

Unfortunately it'll be at least a couple of weeks before we get a chance to roll out the changes to the PDF datasheets (*I know* -- we're working on that!), so hang tight until then. Fortunately this issue is well-written and should serve as a bandaid to help folks who encounter these issues until then.
