### ISSUE TITLE
Spelling raspberry-pi-pico-c-sdk

### ISSUE THREAD

**Issue by ekholm** [raspberrypi/pico-feedback#410]
https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf
page 494
reqsources -> resources

**Comment by lurch** [comment]
This was already fixed in https://github.com/raspberrypi/pico-sdk/pull/1845/commits/0f2501c4093b5e4657b0e393673b4f803e50ff6d (as part of https://github.com/raspberrypi/pico-sdk/pull/1845 ), but this change won't get reflected in the C-SDK PDF until the next time the `master` version of pico-sdk updates (which will correspond to pico-sdk release 2.0.1 - and AFAIK there's no ETA for that yet).
