### ISSUE TITLE
Typo on page 196 in RP2040 DATASHEET

### ISSUE THREAD

**Issue by JanHuygh** [raspberrypi/pico-feedback#94]
On page 196 in the RP2040 DATASHEET the first reference to the SDK is printed twice.

**Comment by aallan** [comment]
Issue transfered to `pico-feedback`

**Comment by Wren6991** [comment]
Thanks, this is caused by a toolchain bug. Now fixed upstream, will appear in the next docs release.

**Comment by JamesH65** [comment]
How do you move an issue from one repo to another?

**Comment by aallan** [comment]
> How do you move an issue from one repo to another?

Option is available at the bottom of the right-hand sidebar. Might only be possible because I'm a Github admin for the organisation though?

<img width="334" alt="Screenshot 2021-02-16 at 16 36 29" src="https://user-images.githubusercontent.com/53625/108093011-2c33aa00-7075-11eb-949e-d1612b1fd57d.png">
